name: Migrate Repos

on:
  workflow_dispatch:

jobs:
  migrate:
    runs-on: ubuntu-latest
    env:
      SOURCE_PAT_USER: ${{ secrets.SOURCE_PAT_USER }}
      SOURCE_PAT_TOKEN: ${{ secrets.SOURCE_PAT_TOKEN }}
      DEST_PAT_USER: ${{ secrets.DEST_PAT_USER }}
      DEST_PAT_TOKEN: ${{ secrets.DEST_PAT_TOKEN }}
     
    steps:
      - name: Configure Git Authentication
        run: git config --global url."https://Meena-1601:${{ secrets.SOURCE_PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - name: Configure Destination Authentication
        run: git config --global url."https://meenasubashri1998-code:${{ secrets.DEST_PAT_TOKEN }}@github.com/".insteadOf "https://github.com/"
      - uses: actions/checkout@v4
      - run: bash scripts/migrate-repos.sh
      
