name: Migrate Repositories

on:
  workflow_dispatch:
    inputs:
      source_pat:
        description: "Source GitHub PAT"
        required: true
      dest_pat:
        description: "Destination GitHub PAT"
        required: true
      source_user:
        description: "Source GitHub Username"
        required: true
      dest_user:
        description: "Destination GitHub Username"
        required: true

jobs:
  migrate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Execute Shell Script
        env:
          SOURCE_PAT_TOKEN: ${{ github.event.inputs.source_pat }}
          DEST_PAT_TOKEN: ${{ github.event.inputs.dest_pat }}
          SOURCE_PAT_USER: ${{ github.event.inputs.source_user }}
          DEST_PAT_USER: ${{ github.event.inputs.dest_user }}
        run: |
          chmod +x scripts/migrate-repos.sh
          bash scripts/migrate-repos.sh
